# Generated by Django 3.0.3 on 2020-02-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.ImageField(upload_to='')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boe_screen.Image')),
            ],
        ),
    ]
