# Generated by Django 2.2.3 on 2020-03-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.TextField(max_length=100)),
                ('image', models.TextField(null=True)),
                ('time', models.DateTimeField(null=True)),
                ('mask', models.TextField(null=True)),
                ('pred', models.PositiveIntegerField(null=True)),
                ('size', models.TextField(max_length=20, null=True)),
                ('area', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProdLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_line_name', models.TextField(max_length=100)),
                ('image_size', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProdLineClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('value', models.PositiveIntegerField(default=0)),
                ('prod_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boe_screen.ProdLine')),
            ],
        ),
        migrations.CreateModel(
            name='ImageClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('value', models.PositiveIntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boe_screen.Image')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='prod_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boe_screen.ProdLine'),
        ),
    ]
