# Generated by Django 2.2.3 on 2020-03-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boe_screen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='weight1',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='weight2',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
