# Generated by Django 2.2.3 on 2020-03-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boe_screen', '0002_auto_20200321_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodline',
            name='count1',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='prodline',
            name='count2',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
