# Generated by Django 2.2.3 on 2020-03-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boe_screen', '0002_auto_20200319_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='area',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='mask',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
