# Generated by Django 2.2.3 on 2020-03-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boe_screen', '0003_auto_20200319_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='area',
            field=models.IntegerField(default=0),
        ),
    ]
