# Generated by Django 2.2.3 on 2020-03-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boe_screen', '0003_auto_20200321_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodline',
            name='avg_bad_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='prodline',
            name='avg_dirt_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='prodline',
            name='max_bad_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prodline',
            name='max_dirt_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prodline',
            name='min_bad_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prodline',
            name='min_dirt_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
