# Generated by Django 2.2.3 on 2020-03-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boe_screen', '0004_auto_20200329_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodline',
            name='avg_bad_size',
        ),
        migrations.RemoveField(
            model_name='prodline',
            name='avg_dirt_size',
        ),
        migrations.AddField(
            model_name='prodline',
            name='sum_bad_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prodline',
            name='sum_dirt_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
