# Generated by Django 2.2.3 on 2020-04-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boe_screen', '0006_auto_20200403_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texture',
            name='min_bad_size',
            field=models.PositiveIntegerField(default=1101600),
        ),
        migrations.AlterField(
            model_name='texture',
            name='min_dirt_size',
            field=models.PositiveIntegerField(default=1101600),
        ),
    ]
