# Generated by Django 2.2.3 on 2020-04-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boe_screen', '0007_auto_20200416_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.TextField(null=True),
        ),
    ]
